name: flutter_base01
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  crypto: ^3.0.7
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  delayed_display: ^2.0.0
  file_picker: ^10.3.8
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.3
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  just_audio: ^0.10.5
  mobile_scanner: ^7.1.4
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  qr_flutter: ^4.1.0
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  simple_animations: ^5.2.0
  sqflite: ^2.4.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
# dart run change_app_package_name:main com.tu_nombre.nombre_de_la_app
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/samicon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/sounds/
